web:
  build: .
  ports:
    - "8000:80"
    - "8001:9000"
  links:
    - db
    # - memcache
    # - redis
  volumes:
    - webroot:/srv/www
    - uploads:/srv/www/uploads
    - /root/.wp-cli/cache
  environment:
    SITE_URL: http://localhost:8000
    WP_DEBUG: 1
  command: supervisord -e debug
db:
  image: mysql
  ports:
    - "8002:3306"
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
# Uncomment the appropriate object cache:
# memcache:
#   image: octohost/memcached
#   command: memcached -m 128 -u daemon -l 0.0.0.0 -v
#   ports:
#     - '8003:11211'
# redis:
#   image: redis:2.8.19
#   ports:
#     - '8004:6379'
